media:
  input: public
  output: /
content:
  - name: bits
    label: Bits n Bobs.
    type: collection
    path: src/pages/cms
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text
